---
- hosts: client.localdomain
  become: yes
  roles:
     - dbbackup
     - client
  vars_files:
    - vars.yml
  vars_prompt:
    - name: mysql_root_password
      prompt: "Please enter your MySQL root password"
      private: yes

- hosts: master.localdomain
  become: yes
  roles:
     - server
  vars_files:
    - vars.yml